### ISSUE TITLE
Cant handle TS change.

### ISSUE THREAD

**Issue by ErenKrt** [guushamann/Todo-tRPC-Vue3#1]
Hello, the change I made on the server side does not detect the client until I close the project and open it and am using VSCode.

![alt text](https://i.ibb.co/M20tyk6/resim-2023-02-12-233007831.png)

**Comment by guushamann** [comment]
Hi @ErenKrt ,
did you install the volar extension, and disabled vetur, if it is installed

for me it works fine, your screenshot is very small so i cannot see what the error is

**Comment by ErenKrt** [comment]
Hello again, yeah i have volar and im not using vetur.
I will add some SS from my extension.

Extensions:
![Code_j8oc1QR7rI](https://user-images.githubusercontent.com/26926124/218853770-e9a67234-4f1f-4b33-a352-50a1f2b9d445.png)
![Code_vLnRAdxEFN](https://user-images.githubusercontent.com/26926124/218853775-95806e27-e674-4606-b5e6-de883d7fa457.png)

Router error:
![Code_Mp5kdrvAow](https://user-images.githubusercontent.com/26926124/218853810-8b256e2f-e066-4acc-bcea-0108429ff089.png)

All of:

![Code_q12WnAle0F](https://user-images.githubusercontent.com/26926124/218853848-4eeeceb7-b65e-4404-89f0-e388a41e6ac6.png)

**Comment by guushamann** [comment]
I think i know what the problem is. i see a node_modules folder in your api-server folder.

A rule for npm workspaces is: Do not run npm install on the seperate apps.

see tutorial for working with workspaces
[workspaces tutorial](https://ruanmartinelli.com/posts/npm-7-workspaces-1)

to solve the problem, go to the root of the monorepo and run:
`npx npkill` to delete all node_module folders in the monorepo
then from monorepo root:
`npm install`
`npm run dev`

i also recommend to open the whole monorepo in vscode

**Comment by ErenKrt** [comment]
i deleted all node_modules and happens same thing.
When i open whole monorepo in vscode works perfect. I thinks this bug happens on VSCode

**Comment by guushamann** [comment]
Nice!
